# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-31 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='question_text',
            new_name='problem_text',
        ),
    ]
