# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 15:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0010_auto_20160624_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
