# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0011_auto_20160624_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
