# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 11:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0012_auto_20160625_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='interview_questions.Problem'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
