# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0013_auto_20160625_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_questions.Problem'),
        ),
    ]
