# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-09 09:45
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0019_auto_20160709_0859'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reply',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
