# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0020_auto_20160709_0945'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='problem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reply',
            managers=[
            ],
        ),
    ]
