# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 09:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0021_auto_20160710_0921'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='problem',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
