# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0026_auto_20160711_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_questions.Votes'),
        ),
    ]
