# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0027_auto_20160711_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='total_votes',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='vote',
        ),
        migrations.DeleteModel(
            name='Votes',
        ),
    ]
