# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0029_auto_20160711_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_questions.Votes'),
        ),
        migrations.AddField(
            model_name='reply',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_questions.Votes'),
        ),
    ]
