# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_questions', '0032_auto_20160803_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='topic',
            name='screenname',
            field=models.CharField(max_length=80),
        ),
    ]
